# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/demo',
                'doc_host': 'https://jbwhit.github.io',
                'git_url': 'https://github.com/jbwhit/demo',
                'lib_path': 'demo'},
  'syms': {'demo.core': {'demo.core.foo': ('core.html#foo', 'demo/core.py')}}}
